In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('nba_games.csv', index_col=0)

In [3]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,16.8,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17835,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
17836,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
17837,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
17838,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
17839,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

Fixing Data Index and sort

In [4]:
df = df.sort_values('date')

In [6]:
df = df.reset_index(drop=True)

In [7]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
1,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
2,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
3,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
4,240.0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17835,240.0,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,...,33.3,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False
17836,240.0,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,...,12.7,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True
17837,240.0,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,...,19.3,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False
17838,240.0,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,...,25.1,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True
17839,240.0,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,...,33.3,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False

Delete Duplicate collumns

In [8]:
del df['mp.1']
del df['mp_opp.1']
del df['index_opp']

In [9]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
1,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
4,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17835,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,0.800,...,33.3,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False
17836,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,0.853,...,12.7,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True
17837,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,0.793,...,19.3,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False
17838,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,0.833,...,25.1,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True
17839,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,0.846,...,33.3,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False

In [11]:
def add_target(team):
    team['target'] = team['won'].shift(-1)
    return team

df = df.groupby('team', group_keys=False).apply(add_target)

/var/folders/gt/gmnl67y90v9dp1vkkdgnmdzc0000gn/T/ipykernel_34608/514775512.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('team', group_keys=False).apply(add_target)

In [12]:
df[df['team'] == 'WAS']

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
19,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,0.600,...,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True,True
49,240.0,35.0,68.0,0.515,12.0,21.0,0.571,36.0,44.0,0.818,...,32.4,138.0,122.0,MIL,113,1,2016,2015-10-30,True,False
69,240.0,38.0,90.0,0.422,6.0,22.0,0.273,28.0,33.0,0.848,...,28.7,153.0,108.0,NYK,117,0,2016,2015-10-31,False,True
121,240.0,42.0,87.0,0.483,8.0,23.0,0.348,10.0,14.0,0.714,...,30.0,160.0,109.0,SAS,99,0,2016,2015-11-04,True,False
166,240.0,36.0,88.0,0.409,8.0,25.0,0.320,18.0,23.0,0.783,...,41.6,146.0,103.0,BOS,118,1,2016,2015-11-06,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17469,240.0,38.0,82.0,0.463,8.0,21.0,0.381,18.0,20.0,0.900,...,34.4,245.0,116.0,BOS,144,1,2022,2022-04-03,False,True
17490,240.0,56.0,101.0,0.554,13.0,30.0,0.433,7.0,14.0,0.500,...,32.8,168.0,132.0,MIN,114,1,2022,2022-04-05,True,False
17506,240.0,42.0,86.0,0.488,10.0,35.0,0.286,9.0,11.0,0.818,...,60.2,159.0,114.0,ATL,118,1,2022,2022-04-06,False,False
17534,240.0,35.0,69.0,0.507,9.0,28.0,0.321,13.0,17.0,0.765,...,35.5,135.0,104.0,NYK,114,0,2022,2022-04-08,False,False
17579,240.0,42.0,94.0,0.447,8.0,23.0,0.348,16.0,26.0,0.615,...,37.3,161.0,118.0,CHO,124,1,2022,2022-04-10,False,NaN

In [14]:
df['target'][pd.isnull(df['target'])] = 2

/var/folders/gt/gmnl67y90v9dp1vkkdgnmdzc0000gn/T/ipykernel_34608/3405584470.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['target'][pd.isnull(df['target'])] = 2
/var/folders/gt/gmnl67y90v9dp1vkkdgnmdzc0000gn/T/ipykernel_34608/3405584470.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'][pd.isnull(df['target'])] = 2

In [15]:
df['target'] = df['target'].astype(int, errors = 'ignore')

In [16]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
1,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
4,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17835,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,0.800,...,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False,0
17836,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,0.853,...,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True,0
17837,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,0.793,...,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False,1
17838,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,0.833,...,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True,2
17839,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,0.846,...,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False,2

In [17]:
df['won'].value_counts()

won
False    8920
True     8920
Name: count, dtype: int64

In [18]:
df['target'].value_counts()

target
1    8906
0    8904
2      30
Name: count, dtype: int64

In [19]:
nulls = pd.isnull(df)

In [20]:
nulls = nulls.sum()

In [22]:
nulls[nulls>0]

+/-             17840
mp_max          17840
mp_max.1        17840
+/-_opp         17840
mp_max_opp      17840
mp_max_opp.1    17840
dtype: int64

We are working on eliminate the null values

In [37]:
df.columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=148)

In [41]:
# valid_columns = df.columns[~df.columns.isin(nulls.index)]
valid_columns = df.columns[~df.columns.isin(nulls[nulls > 0].index)]

In [42]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [43]:
df = df[valid_columns].copy()

In [44]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
1,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
2,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
3,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
4,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17835,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,0.800,...,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False,0
17836,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,0.853,...,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True,0
17837,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,0.793,...,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False,1
17838,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,0.833,...,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True,2
17839,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,0.846,...,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False,2

In [45]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction='forward', cv=split)

In [46]:
removed_columns = ['season', 'date', 'won', 'target', 'team', 'team_opp']

In [47]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [50]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [51]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.317647,DET,0.403846,0.0,2016,2015-10-27,False,1
1,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.505882,NOP,0.298077,0.0,2016,2015-10-27,True,1
2,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.317647,CHI,0.317308,1.0,2016,2015-10-27,False,1
3,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.088575,0.232227,0.329412,CLE,0.298077,0.0,2016,2015-10-27,True,1
4,0.0,0.409091,0.529412,0.277512,0.413793,0.378788,0.491686,0.441860,0.396825,0.730455,...,0.150193,0.800948,0.517647,ATL,0.288462,1.0,2016,2015-10-27,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17835,0.0,0.477273,0.264706,0.583732,0.310345,0.287879,0.464371,0.162791,0.142857,0.766628,...,0.483954,0.549763,0.576471,BOS,0.442308,1.0,2023,2023-05-25,False,0
17836,0.0,0.340909,0.264706,0.399522,0.241379,0.469697,0.237530,0.651163,0.523810,0.828471,...,0.064185,0.232227,0.552941,MIA,0.375000,1.0,2023,2023-05-27,True,0
17837,0.0,0.318182,0.485294,0.205742,0.482759,0.393939,0.554632,0.511628,0.444444,0.758460,...,0.138639,0.355450,0.611765,BOS,0.384615,0.0,2023,2023-05-27,False,1
17838,0.0,0.522727,0.382353,0.523923,0.482759,0.363636,0.593824,0.093023,0.079365,0.805134,...,0.173299,0.829384,0.517647,BOS,0.192308,1.0,2023,2023-05-29,True,2
17839,0.0,0.295455,0.323529,0.289474,0.310345,0.575758,0.254157,0.232558,0.190476,0.820303,...,0.138639,0.308057,0.305882,MIA,0.375000,0.0,2023,2023-05-29,False,2

In [52]:
sfs.fit(df[selected_columns], df['target'])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [53]:
predictors = list(selected_columns[sfs.get_support()])

In [54]:
predictors

['mp',
 '3p%',
 'ft%',
 'pf',
 'trb%',
 'usg%',
 'ft_max',
 'ft%_max',
 'pf_max',
 '+/-_max',
 'drb%_max',
 'tov%_max',
 'usg%_max',
 'mp_opp',
 'blk_opp',
 'trb%_opp',
 'usg%_opp',
 'fg_max_opp',
 '3p%_max_opp',
 'ft%_max_opp',
 'ast_max_opp',
 'stl_max_opp',
 'blk_max_opp',
 'pf_max_opp',
 'pts_max_opp',
 'drb%_max_opp',
 'ast%_max_opp',
 'stl%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp']

In [57]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data['season'].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data['season'] < season]
        test = data[data['season'] == season ]
        
        model.fit(train[predictors], train['target'])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        
        combined = pd.concat([test['target'], preds], axis=1)
        combined.columns = ['actual', 'prediction']
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

Training Model

In [58]:
predictions = backtest(df, rr, predictors)

In [59]:
predictions

       actual  prediction
5250        1           1
5251        1           0
5252        1           0
5253        0           0
5254        0           0
...       ...         ...
17835       0           0
17836       0           1
17837       1           0
17838       2           1
17839       2           1

[12590 rows x 2 columns]

Prediction Results

In [63]:
from sklearn.metrics import accuracy_score

accuracy_score(predictions['actual'], predictions['prediction'])

0.5452740270055599